### PR TITLE
Adding common bitcoin RPC API methods

### PR DESCRIPTION
**Pull request by renuzit**
Zcash supports both Bitcoin and Zcash RPC API commands. This commit adds a few of the common methods that are found in bitcoin RPC API.

### CODE REVIEW

**Comment by renuzit** [comment]
BTW, I love your library! It's the best one I could find right now.

**Comment by montyanderson** [comment]
Thanks for this!
I think I might add an ES6 Proxy like I did with [stdrpc](https://github.com/montyanderson/stdrpc).

**Comment by renuzit** [comment]
What would be the advantage of doing that?

**Comment by renuzit** [comment]
If I could suggest a couple of improvements, I would probably suggest using a true test framework using mocks, maybe something like mocha and nock.

**Pull request merged**
